### ISSUE TITLE
NROP CR status is not aligned with the specs

### ISSUE THREAD

**Issue by shajmakh** [openshift-kni/numaresources-operator#920]
steps to reproduce: 
- add tolerations to spec
- delete them and see the status still contains them 
- however, RTE pods are restarted with no tolerations so it seems only a wrong reporting in NROP CR status  
this is not particularly to Tolerations but can happen with the other config fields too. 

```
spec:
  logLevel: Trace
  nodeGroups:
  - machineConfigPoolSelector:
      matchLabels:
        pools.operator.machineconfiguration.openshift.io/worker: ""
status:
  conditions:
  - lastTransitionTime: "2024-04-10T14:31:37Z"
    message: ""
    reason: Available
    status: "True"
    type: Available
  - lastTransitionTime: "2024-04-10T14:31:37Z"
    message: ""
    reason: Upgradeable
    status: "True"
    type: Upgradeable
  - lastTransitionTime: "2024-04-10T14:31:37Z"
    message: ""
    reason: Progressing
    status: "False"
    type: Progressing
  - lastTransitionTime: "2024-04-10T14:31:37Z"
    message: ""
    reason: Degraded
    status: "False"
    type: Degraded
  daemonsets:
  - name: numaresourcesoperator-worker
    namespace: openshift-numaresources
  machineconfigpools:
  - config:
      infoRefreshMode: Periodic
      infoRefreshPeriod: 1s
      podsFingerprinting: Enabled
      tolerations:
      - effect: NoSchedule
        key: sriov
        operator: Equal
        value: "true"
    name: worker
```
